### PR TITLE
Fixes for currents issues

### PR DESCRIPTION
**Pull request by mathias-luedtke**
- Decouple resend form watchdog
- use effort/currents to limits finger motions

**version should not be mixed betweend server and clients**

### CODE REVIEW

**Comment by mathias-luedtke** [comment]
rebased to #2 and #8

**Comment by mathias-luedtke** [comment]
ready for test

**Comment by NadiaHG** [comment]
CR: OK
Test on cob4-5: OK

**Comment by floweisshardt** [comment]
FR: OK

**Pull request merged**
