### PR TITLE
low-level cob_hand_bridge with ROS serial server 

### PR DESCRIPTION
**Pull request by mathias-luedtke**
(See README.md for details)

### CODE REVIEW

**Comment by fmessmer** [comment]
Can't really review this PR....beside FR ok

Just one questions:
As the repo is public and only contains one driver package, why does `cob_hand_bridge` not go into `cob_driver`?

**Comment by mathias-luedtke** [comment]
This repo was meant for all software that is running on the raspberry pi (ARM architecture!) in the hand, including upstart scripts and other system helpers etc.
I would like to keep it this way until the final software layout is settled since we are still testing the various alternatives.

`cob_hand_bridge` is currently just the low-level part that bridges ROS into the raspberry.
The high-level part (bringup-services, joins states, action interface) is still missing.

**Comment by mathias-luedtke** [comment]
@ipa-nhg: as tested with hardware today

**Comment by NadiaHG** [comment]
FR: OK
Test on cob4-5 : OK

**Comment by mathias-luedtke** [comment]
Known limitations: 
- Bug + Fix: #2 
- recover does not work: TODO
- single point trajectories: TBD

**Pull request merged**
