### PR TITLE
Fix for failure if already at target

### PR DESCRIPTION
**Pull request by mathias-luedtke**
Should send success even if started at target.
(includes #1)

### CODE REVIEW

**Comment by NadiaHG** [comment]
Test on cob4-5 : OK

**Comment by mathias-luedtke** [comment]
Further test needed to verify that trajectory duration matches the call blocking

**Comment by mathias-luedtke** [comment]
rebased to #8

**Comment by mathias-luedtke** [comment]
works as expected, timing matches the trajectory

**Comment by floweisshardt** [comment]
FR: OK

**Pull request merged**
