### PR TITLE
properly handle re-init after restart

### PR DESCRIPTION
**Pull request by mathias-luedtke**

### CODE REVIEW

**Comment by mathias-luedtke** [comment]
please squash-merge

**Comment by NadiaHG** [comment]
I tested this on the robot, unfortunately something is still missed, now the init service return always `False`  , also after a new start

**Comment by mathias-luedtke** [comment]
The client can only be [initialized once](https://github.com/ipa320/cob_hand/blob/indigo_dev/cob_hand_bridge/client/src/bridge.cpp#L40).
So just adjust the logic as you need it.

**Comment by NadiaHG** [comment]
Thanks @ipa-mdl 
Tested on the robot and working

**Review by NadiaHG — APPROVED** [review]

**Pull request merged**
